// ============================================================
// Community Medicine Examination System
// Offline Excel -> JSON / Embedded-JS Rebuild Tool
//
// Runs entirely in the browser via the bundled SheetJS library
// (tools/vendor/xlsx.full.min.js) — no server, no install, no
// internet connection. Reads QuestionBank.xlsx and reproduces the
// same output tools/build.R does, validated field-by-field against
// the committed data/questions.json and data/settings.json:
//
//   - Question sheets need no extra type coercion; SheetJS's own
//     per-cell type inference already matches (Question_No comes
//     through as a string, Marks_A/Total_Marks as numbers).
//   - The Settings sheet DOES need explicit handling: R's readxl
//     forces a whole column to text the moment any value in it is
//     non-numeric, which is why every value in the existing
//     settings.json is a string even for numbers like "20". SheetJS
//     parses each cell independently and won't do this on its own,
//     so every settings value is deliberately String()-coerced here.
//   - Biostatistics and OSPE are missing Answer_Key_C in the real
//     workbook; every row is null-filled for Answer_Key_A/B/C, same
//     as build.R's ensure_answer_keys().
// ============================================================


const SECTION_SHEETS = {

    clinical: "Clinical_Case",

    epidemiology: "Epidemiology",

    biostatistics: "Biostatistics",

    ospe: "OSPE",

    spotter: "Spotter"

};

const REQUIRED_SHEETS =
    Object.values(SECTION_SHEETS).concat(["Settings"]);

const ANSWER_KEY_FIELDS =
    ["Answer_Key_A", "Answer_Key_B", "Answer_Key_C"];


// ------------------------------------------------------------
// Parse a workbook (ArrayBuffer) into { questions, settings }
// ------------------------------------------------------------

function parseWorkbook(arrayBuffer) {

    const workbook = XLSX.read(arrayBuffer, { type: "array" });

    const missingSheets = REQUIRED_SHEETS.filter(

        name => workbook.SheetNames.indexOf(name) === -1

    );

    if (missingSheets.length > 0) {

        throw new Error(

            "Missing expected sheet(s): " + missingSheets.join(", ") +
            ". Found: " + workbook.SheetNames.join(", ")

        );

    }

    const questions = {};

    const counts = {};

    Object.keys(SECTION_SHEETS).forEach(function(sectionKey){

        const sheetName = SECTION_SHEETS[sectionKey];

        const rows =
            XLSX.utils.sheet_to_json(

                workbook.Sheets[sheetName],

                { defval: null }

            );

        rows.forEach(function(row){

            ANSWER_KEY_FIELDS.forEach(function(field){

                if (!(field in row)) row[field] = null;

            });

        });

        questions[sectionKey] = rows;

        counts[sectionKey] = summarizeSection(sectionKey, rows);

    });

    const settingsRows =
        XLSX.utils.sheet_to_json(

            workbook.Sheets.Settings,

            { defval: null }

        );

    const settings = {};

    settingsRows.forEach(function(row){

        if (!row.Parameter) return;

        settings[row.Parameter] = coerceSettingValue(row.Value);

    });

    return { questions, settings, counts };

}


// R's readxl reads a boolean-typed cell as a logical, and stringifying
// it (as the character-coercion below already does for every settings
// value) produces "TRUE"/"FALSE" — R's own uppercase convention.
// SheetJS returns a native JS boolean for the same cell, and JS's
// String(true) is lowercase "true". Coerce explicitly so the two tools
// agree byte-for-byte rather than differing only by case.
function coerceSettingValue(value) {

    if (value === null) return null;

    if (typeof value === "boolean") return value ? "TRUE" : "FALSE";

    return String(value);

}

function summarizeSection(sectionKey, rows) {

    const itemType =
        sectionKey === "spotter" ? "Spotter_Slide" : "Question";

    const items = rows.filter(r => r.Item_Type === itemType).length;

    const headers =
        rows.filter(r => r.Item_Type === "Section_Header").length;

    return { total: rows.length, items, headers };

}


// ------------------------------------------------------------
// Output builders
// ------------------------------------------------------------

function buildQuestionsJSON(parsed) {

    return JSON.stringify(parsed.questions, null, 2);

}

function buildSettingsJSON(parsed) {

    return JSON.stringify(parsed.settings, null, 2);

}

function buildEmbeddedJS(parsed) {

    return (

        "// ============================================================\n" +
        "// Community Medicine Examination System\n" +
        "// Embedded Application Data — generated by Rebuild Data.html\n" +
        "// Generated: " + new Date().toISOString() + "\n" +
        "//\n" +
        "// Loaded by index.html before js/loader.js. When this defines\n" +
        "// EMBEDDED_APP_DATA, loader.js uses it directly instead of\n" +
        "// fetch()-ing data/questions.json and data/settings.json, so\n" +
        "// the app works from a bare file:// double-click.\n" +
        "// ============================================================\n\n" +
        "const EMBEDDED_APP_DATA = {\n" +
        "    questions: " + JSON.stringify(parsed.questions, null, 4) + ",\n" +
        "    settings: " + JSON.stringify(parsed.settings, null, 4) + "\n" +
        "};\n"

    );

}


// ------------------------------------------------------------
// Saving
// ------------------------------------------------------------

function downloadFile(filename, content) {

    const blob = new Blob([content], { type: "text/plain" });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;

    a.download = filename;

    document.body.appendChild(a);

    a.click();

    document.body.removeChild(a);

    URL.revokeObjectURL(url);

}

async function writeFileToDirectory(dirHandle, filename, content) {

    const fileHandle =
        await dirHandle.getFileHandle(filename, { create: true });

    const writable = await fileHandle.createWritable();

    await writable.write(content);

    await writable.close();

}

async function saveOutputs(outputs) {

    // File System Access API (Chromium/Edge): pick the data/ folder
    // once, write all three files directly into it, no manual moving.
    if (window.showDirectoryPicker) {

        const dirHandle = await window.showDirectoryPicker();

        for (const filename in outputs) {

            await writeFileToDirectory(dirHandle, filename, outputs[filename]);

        }

        return "written";

    }

    // Fallback: plain downloads, to be moved into data/ by hand.
    for (const filename in outputs) {

        downloadFile(filename, outputs[filename]);

    }

    return "downloaded";

}
